const IMAGES_BASE_PATH = "/assets/images";
const GENERAL_IMAGES_BASE_PATH = `${IMAGES_BASE_PATH}/general`;
const TEACHER_IMAGES_BASE_PATH = `${IMAGES_BASE_PATH}/teacher`;
const TEACHER_DASHBOARD_IMAGES_BASE_PATH = `${TEACHER_IMAGES_BASE_PATH}/dashboard`;
const TEACHER_ASSIGNMENT_IMAGES_BASE_PATH = `${TEACHER_IMAGES_BASE_PATH}/assignments`;
const TEACHER_ATTENDANCE_IMAGES_BASE_PATH = `${TEACHER_IMAGES_BASE_PATH}/attendance`;
const TEACHER_CHARACTER_IMAGES_BASE_PATH = `${TEACHER_IMAGES_BASE_PATH}/character`;
const TEACHER_SEATING_IMAGES_BASE_PATH = `${TEACHER_IMAGES_BASE_PATH}/seating`;
const TEACHER_COMMUNICATE_IMAGES_BASE_PATH = `${TEACHER_IMAGES_BASE_PATH}/communicate`;
const MENU_IMAGES_BASE_PATH = `${IMAGES_BASE_PATH}/menu`;

export const generalImages = {
  dreaMetrixLogo: `${GENERAL_IMAGES_BASE_PATH}/logo.png`,
  assignments: `${GENERAL_IMAGES_BASE_PATH}/assignments.svg`,
  attendance: `${GENERAL_IMAGES_BASE_PATH}/attendance.svg`,
  character: `${GENERAL_IMAGES_BASE_PATH}/character.svg`,
  communicate: `${GENERAL_IMAGES_BASE_PATH}/communicate.svg`,
  test_prep: `${GENERAL_IMAGES_BASE_PATH}/test_prep.svg`,
  gradebook: `${GENERAL_IMAGES_BASE_PATH}/gradebook.svg`,
  home: `${GENERAL_IMAGES_BASE_PATH}/home.svg`,
  polls: `${GENERAL_IMAGES_BASE_PATH}/polls.svg`,
  reports: `${GENERAL_IMAGES_BASE_PATH}/reports.svg`,
  seating: `${GENERAL_IMAGES_BASE_PATH}/seating.svg`,
  teach: `${GENERAL_IMAGES_BASE_PATH}/teach.svg`,
  add: `${GENERAL_IMAGES_BASE_PATH}/add.svg`,
  calculations: `${GENERAL_IMAGES_BASE_PATH}/calculations.svg`,
  layout: `${GENERAL_IMAGES_BASE_PATH}/layout.svg`,
  print: `${GENERAL_IMAGES_BASE_PATH}/print.svg`,
  filter: `${GENERAL_IMAGES_BASE_PATH}/filter.svg`,
  status: `${GENERAL_IMAGES_BASE_PATH}/status.svg`,
  arrow_down: `${GENERAL_IMAGES_BASE_PATH}/arrow_down.png`,
  student: `${GENERAL_IMAGES_BASE_PATH}/student.png`,
  student2: `${GENERAL_IMAGES_BASE_PATH}/student2.png`,
  library: `${GENERAL_IMAGES_BASE_PATH}/library.svg`,
  rewards: `${GENERAL_IMAGES_BASE_PATH}/rewards.svg`,
  tutor: `${GENERAL_IMAGES_BASE_PATH}/tutor.svg`,
  attendance_ok: `${GENERAL_IMAGES_BASE_PATH}/attendance_ok.png`,
  question_mark: `${GENERAL_IMAGES_BASE_PATH}/question_mark.png`,
  red_cross: `${GENERAL_IMAGES_BASE_PATH}/red_cross.png`,
  classes: `${GENERAL_IMAGES_BASE_PATH}/classes.png`,
  default_user: `${GENERAL_IMAGES_BASE_PATH}/default_user.png`,
  no_data: `${GENERAL_IMAGES_BASE_PATH}/no_data.png`,
};

export const teacherImages = {
  ai: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/ai.svg`,
  ai1: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/ai-1.svg`,
  ai2: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/ai-2.svg`,
  done: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/done.svg`,
  edit: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/edit.svg`,
  information: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/information.svg`,
  message: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/message.svg`,
  profile: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/profile.svg`,
  settings: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/settings.svg`,
  upload: `${TEACHER_DASHBOARD_IMAGES_BASE_PATH}/upload.svg`,
  feedback: `${TEACHER_ASSIGNMENT_IMAGES_BASE_PATH}/feedback.svg`,
  files: `${TEACHER_ASSIGNMENT_IMAGES_BASE_PATH}/files.svg`,
  report: `${TEACHER_ATTENDANCE_IMAGES_BASE_PATH}/report.svg`,
  calendar: `${TEACHER_ATTENDANCE_IMAGES_BASE_PATH}/calendar.svg`,
  save: `${TEACHER_ATTENDANCE_IMAGES_BASE_PATH}/save.svg`,
  print: `${TEACHER_ATTENDANCE_IMAGES_BASE_PATH}/print.svg`,
  down: `${TEACHER_CHARACTER_IMAGES_BASE_PATH}/down.svg`,
  up: `${TEACHER_CHARACTER_IMAGES_BASE_PATH}/up.svg`,
  autogenerate: `${TEACHER_SEATING_IMAGES_BASE_PATH}/autogenerate.svg`,
  conditions: `${TEACHER_SEATING_IMAGES_BASE_PATH}/conditions.svg`,
  distracted: `${TEACHER_SEATING_IMAGES_BASE_PATH}/distracted.svg`,
  glass: `${TEACHER_SEATING_IMAGES_BASE_PATH}/glass.svg`,
  manual: `${TEACHER_SEATING_IMAGES_BASE_PATH}/manual.svg`,
  seat_left: `${TEACHER_SEATING_IMAGES_BASE_PATH}/seat_left.svg`,
  seat_right: `${TEACHER_SEATING_IMAGES_BASE_PATH}/seat_right.svg`,
  all_parents: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/all_parents.svg`,
  attachment: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/attachment.svg`,
  compose: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/compose.svg`,
  delete: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/delete.svg`,
  external: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/external.svg`,
  individual_parent: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/individual_parent.svg`,
  whole_class: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/whole_class.svg`,
  voice_note: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/voice_note.svg`,
  schedule: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/schedule.svg`,
  reply: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/reply.svg`,
  play: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/play.svg`,
  pause: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/pause.svg`,
  next: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/next.svg`,
  new_group: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/new_group.svg`,
  individual_student: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/individual_student.svg`,
  attachement: `${TEACHER_COMMUNICATE_IMAGES_BASE_PATH}/attachement.svg`,
};

export const menuImages = {
  assignments: `${MENU_IMAGES_BASE_PATH}/Assignments.svg`,
  attendance: `${MENU_IMAGES_BASE_PATH}/Attendance.svg`,
  character: `${MENU_IMAGES_BASE_PATH}/Character.svg`,
  child_study: `${MENU_IMAGES_BASE_PATH}/ChildStudy.svg`,
  classes: `${MENU_IMAGES_BASE_PATH}/Classes.svg`,
  communicate: `${MENU_IMAGES_BASE_PATH}/Communicate.svg`,
  digital_library: `${MENU_IMAGES_BASE_PATH}/DigitalLibrary.svg`,
  dream_arcade: `${MENU_IMAGES_BASE_PATH}/DreamArcade.svg`,
  gradebook: `${MENU_IMAGES_BASE_PATH}/Gradebook.svg`,
  polls: `${MENU_IMAGES_BASE_PATH}/Polls.svg`,
  reports: `${MENU_IMAGES_BASE_PATH}/Reports.svg`,
  seating: `${MENU_IMAGES_BASE_PATH}/Seating.svg`,
  teach: `${MENU_IMAGES_BASE_PATH}/Teach.svg`,
  big_braain: `${MENU_IMAGES_BASE_PATH}/BigBraain.svg`,
  plan: `${MENU_IMAGES_BASE_PATH}/Plan.svg`,
  report_card: `${MENU_IMAGES_BASE_PATH}/ReportCard.svg`,
  test_prep: `${MENU_IMAGES_BASE_PATH}/TestPrep.svg`,
};
